backend:
  name: github
  repo: cauvangADMIN/ReplayGameNews
  branch: main
  base_url: https://decap-cms-oauth.vercel.app
  auth_endpoint: auth

media_folder: "images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }